"""Feature Inventory rows, read from the iterations.

I1 = iteration1/index.html and the guest pages it links to (story, worship, events, learn, belong, give, gallery, login).
I2 = iteration2/index.html (signed-in member web app).
Admin Utility, phone.html and the I2 'Notification Playground' (QA-only) are intentionally left out.

Each row: (section, feature, description, where in mockup, who)
who: "GS" = in both, "G" = guest site only, "S" = signed-in app only. Guest / Signed-in default to Yes where present.
"""

INVENTORY = [
    # ---------------------------------------------------------------- Home
    ("Home", "Hero & quick links", "Animated sun-dial hero; links to Live darshan, Calendar/Events, Visit/Donate, Volunteer, Get the app", "I1 #h6 · I2 Home", "GS"),
    ("Home", "Today's Panchang", "Tithi, sunrise/sunset, Pratikraman time, drag-the-sun day clock", "I1 hero · I2 Home", "GS"),
    ("Home", "Thought for Today", "Daily Jain thought", "I1 #today · I2 Home", "GS"),
    ("Home", "Daily Quiz", "Daily multiple-choice question (e.g. five great vows / Ahimsa)", "I1 #today · I2 Home", "GS"),
    ("Home", "Personal greeting", "'Jai Jinendra, <name>' with today's date", "I2 Home", "S"),
    ("Home", "Pending Dues banner", "Total due by date, itemised dues, Pay All Now", "I2 Home", "S"),
    ("Home", "Today's Swamivatsalya", "Sponsor family and Snatra Puja time for today", "I2 Home", "S"),
    ("Home", "Quick Actions", "Shortcuts: Darshan, Donate, Events, Volunteer", "I2 Home", "S"),
    ("Home", "Upcoming events", "Next few events with 'See all' to the calendar", "I2 Home", "S"),
    ("Home", "Center Hours", "Open-now status, daily hours, address", "I2 Home", "S"),
    ("Home", "Latest Announcements", "Pinned and recent JCA posts with link to community feed", "I2 Home", "S"),
    ("Home", "One Roof, Many Paths to Liberation", "Stats counters and the four-floor tower with links to each shrine", "I1 #traditions, #tower", "G"),
    ("Home", "Take Darshan from Any Corner of the World", "Live darshan promo band (button goes to Sign in)", "I1 #live", "G"),
    ("Home", "A Seat Is Waiting for You", "Community teaser: Volunteer/Seva, Youth Group, Seniors Group", "I1 #community", "G"),
    ("Home", "Offerings That Sustain the Sangha", "Quick-donate amounts ($51 / $108 / $251 / $501 / custom) linking to Give", "I1 #give", "G"),
    ("Home", "Moments in Marble & Light", "Photo strip linking to the gallery", "I1 #moments", "G"),
    ("Home", "A Monthly Letter from the Sangha", "Newsletter email subscribe box", "I1 home", "G"),
    ("Home", "Carry the Temple in Your Pocket", "App Store / Google Play preview badges", "I1 #app", "G"),
    # ---------------------------------------------------------------- Worship
    ("Worship", "Explore Worship", "Landing page: 'Five Doorways to the Same Dharma'", "I1 worship.html", "G"),
    ("Worship", "Mahavir Swami Temple", "2nd floor, Shvetambar Murtipujak (Svetambara tradition)", "I1 worship.html#mahavir-temple", "G"),
    ("Worship", "Adinathji Temple", "3rd floor, Digambar tradition", "I1 worship.html#adinath-temple", "G"),
    ("Worship", "Upashray Lecture Hall", "2nd floor, Sthanakvasi (Sthanak Upashray, Terapanthi)", "I1 worship.html#sthanak-upashray", "G"),
    ("Worship", "Shrimad Hall", "3rd floor, Shrimad Rajchandra (Param Krupalu Dev) tradition", "I1 worship.html#shrimad-rajchandra", "G"),
    ("Worship", "Dadawadi", "4th floor, Dadawadi tradition and Asthapad Maha Tirth", "I1 worship.html#dadawadi", "G"),
    ("Worship", "Step Inside, From Anywhere", "Closing band on Worship with visit / virtual tour links", "I1 worship.html#visit", "G"),
    # ---------------------------------------------------------------- Live Darshan
    ("Live Darshan", "Live Darshan streams", "Five shrine streams with LIVE badges and viewer counts (guest site only links to Sign in)", "I2 Live Darshan", "S"),
    ("Live Darshan", "Today's Aarti Schedule", "Mangal Aarti, Snatra Puja, Sandhya Aarti, Bhavna times", "I2 Live Darshan", "S"),
    # ---------------------------------------------------------------- Events
    ("Events", "Calendar", "Month calendar; tap a day to see events (festival/parva days vs JCA events)", "I1 events.html#calendar · I2 Events", "GS"),
    ("Events", "Event detail & schedule", "Event description, hour-by-hour schedule, location and map preview", "I1 events.html · I2 Events", "GS"),
    ("Events", "Parva Days", "List of upcoming parva days with countdown", "I2 Events", "S"),
    ("Events", "Event RSVP", "RSVP / manage RSVP, going count, waitlist with auto-promotion, full-shift fallback to volunteering", "I2 Events", "S"),
    ("Events", "Sponsor this event", "Sponsor button on event detail", "I2 Events", "S"),
    ("Events", "Featured: Paryushan & Das Lakshan", "Featured festival 'Nine Days, One Forgiveness'", "I1 events.html#featured", "G"),
    ("Events", "News & Updates", "Latest-from-the-Center news posts", "I1 events.html#news", "G"),
    ("Events", "Newsletters", "Archive of past issues", "I1 events.html#newsletters · I2 Community Feed", "GS"),
    ("Events", "Email Subscription", "Sign-up for News & Updates e-mails", "I1 events.html#newsletters", "G"),
    ("Events", "Past Events", "Auto-archived events with attendance, amount raised, photos (v1.5)", "I2 Past Events", "S"),
    # ---------------------------------------------------------------- Learn
    ("Learn", "Overview — The Temple, Floor by Floor", "Building dimensions and a tour of each floor and the dining hall", "I1 learn.html#overview", "G"),
    ("Learn", "Scholars", "Acharyas and scholars who visited JCA (2013, 2015) with profiles", "I1 learn.html#scholars", "G"),
    ("Learn", "Lecture Series", "Academic seminar series", "I1 learn.html#lecture-series", "G"),
    ("Learn", "Ashtapad Research", "Mount Ashtapad: concept, crystals and gemstones, ceremonies, research, conclusion", "I1 learn.html#ashtapad", "G"),
    ("Learn", "Library & Pathshala resources", "Pathshala activities, library books, publications & articles, downloads", "I1 learn.html#resources", "G"),
    ("Learn", "Art Gallery", "Cellar-level member art exhibitions, interior themes by floor", "I1 learn.html#art-gallery", "G"),
    ("Learn", "Temple Artwork", "Marble and silver Pat, paintings, third-floor artwork", "I1 learn.html#temple-artwork", "G"),
    ("Learn", "Idols & Pat", "The Pratimas of JCA: 23 idols/devs/devis with descriptions", "I1 learn.html#idols-pat", "G"),
    ("Learn", "Jain Websites", "Curated outside Jain resources", "I1 learn.html#jain-websites", "G"),
    ("Learn", "Jinvani Library", "Searchable scripture, commentary and children's texts; categories, bookmarks, continue reading (v1.5)", "I2 Jinvani Library", "S"),
    ("Learn", "Jain Philosophy — Lessons", "Lesson tracks with progress tracking (v2.0)", "I2 Jain Philosophy", "S"),
    ("Learn", "Jain Philosophy — Pravachan & Lectures", "Video archive by topic, speaker, date (v2.0)", "I2 Jain Philosophy", "S"),
    # ---------------------------------------------------------------- Belong
    ("Belong", "Join the community", "Belong landing page: 'A Place to Grow, Serve & Belong'", "I1 belong.html", "G"),
    ("Belong", "Become a Member", "Membership types and pledges", "I1 belong.html#member", "G"),
    ("Belong", "New Account", "Request-an-account form: name, email, mobile, membership type", "I1 belong.html#account", "G"),
    ("Belong", "Pathshala", "Sunday classes for children; signed-in: Spring Term classes, today's lesson, term fee status, attendance streak", "I1 belong.html#pathshala · I2 Pathshala", "GS"),
    ("Belong", "Pathshala Books", "Books assigned to enrolled children, offline download", "I2 Pathshala", "S"),
    ("Belong", "Enroll a Family Member", "Enrol a child or family member in Pathshala", "I2 Pathshala", "S"),
    ("Belong", "Pathshala Teacher contact", "Teacher details and Send feedback", "I2 Pathshala", "S"),
    ("Belong", "Youth Group", "Guest: teens & young adults (13-25) info. Signed-in: Teen Circle, YJA retreat, group seva (v1.5)", "I1 belong.html#youth · I2 Youth", "GS"),
    ("Belong", "Senior Group", "Wednesday gatherings", "I1 belong.html#senior", "G"),
    ("Belong", "Library (Shelves, Scholars & Silence)", "About the library", "I1 belong.html", "G"),
    ("Belong", "Volunteer Sign Up", "Guest: volunteer interest form. Signed-in: opportunity board, shift sign-up, hours committed, Full state", "I1 belong.html#volunteer · I2 Volunteer & Seva", "GS"),
    ("Belong", "Community Feed", "Announcements and News & Newsletters tabs, emoji reactions", "I2 Community Feed", "S"),
    # ---------------------------------------------------------------- Give
    ("Give", "Give landing", "'Offerings That Sustain the Sangha'", "I1 give.html", "G"),
    ("Give", "Active Causes", "Cause cards with goal/progress and preset amounts ($51/$108/$251/$501/custom)", "I1 give.html#causes · I2 Donate › Causes", "GS"),
    ("Give", "Donate to JCA", "Ways to donate online", "I1 give.html#donate", "G"),
    ("Give", "Donate with Zelle", "Zelle instructions (signed-in: Zelle off-platform option at checkout)", "I1 give.html#donate · I2 Payment", "GS"),
    ("Give", "Sponsor Bhojanshala", "Fund a day of meals; Annadan options (Full Lunch, Snack Seva, Sweet Box, Festival Feast), pick an available Sunday", "I1 give.html#sponsor · I2 Donate › Sponsor Bhojanshala", "GS"),
    ("Give", "Sponsor a Tithi", "Sponsor a calendar date", "I2 Donate", "S"),
    ("Give", "Sponsors of the Month", "Sponsor recognition list", "I2 Donate", "S"),
    ("Give", "Matching Donation", "Employer matching explainer; signed-in: Matching Gifts Program cause", "I1 give.html#matching · I2 Donate", "GS"),
    ("Give", "JCA Cares", "Compassion beyond the walls (guest info page)", "I1 give.html#cares", "G"),
    ("Give", "Where your gift goes", "Accountability: every dollar accounted for", "I1 give.html#accountability", "G"),
    ("Give", "Donate anonymously", "Anonymous giving checkbox", "I2 Donate", "S"),
    ("Give", "Payment checkout", "Summary; Apple Pay, G Pay, Card, PayPal, Bank/ACH; receipt email; save card; 501(c)(3) note", "I2 Payment", "S"),
    ("Give", "Thank you & receipt", "Confirmation, transaction ID, Download Receipt (PDF), Share, Make monthly", "I2 Thank You", "S"),
    ("Give", "My Donation History", "Year/month list of gifts, per-gift receipt, Year-end Statement", "I2 My Donation History", "S"),
    ("Give", "Recurring Seva", "My Subscriptions (edit amount, pause), Set Up New, Popular Plans", "I2 Recurring Seva", "S"),
    # ---------------------------------------------------------------- Gallery
    ("Gallery", "Open the gallery", "Gallery landing: 'Light Falling on Marble'", "I1 gallery.html", "G"),
    ("Gallery", "Photos", "Photo grid", "I1 gallery.html#photos", "G"),
    ("Gallery", "Albums", "Albums by temple and hall", "I1 gallery.html#albums", "G"),
    ("Gallery", "360° Tour", "Nine virtual-tour locations (Temple, Lobby, Mahavir, Upashray, Adinath, Shrimad, Dadawadi, Asthapad, Art Gallery)", "I1 gallery.html#tour", "G"),
    ("Gallery", "Video Gallery", "Link out to the JCA YouTube channel", "I1 nav › Gallery", "G"),
    # ---------------------------------------------------------------- Our Story
    ("Our Story", "Read our story", "Landing: 'A Community That Built a Temple'", "I1 story.html", "G"),
    ("Our Story", "About JCA", "The temple complex: cellar, 2nd, 3rd and 4th floors", "I1 story.html#about-jca", "G"),
    ("Our Story", "JCA History", "Timeline and construction: objectives, site selection, design, plans, contracts, ancillary facilities, at a glance, photo history", "I1 story.html#history", "G"),
    ("Our Story", "JCA Mission", "'Every Path, Equally Honored'", "I1 story.html#mission", "G"),
    ("Our Story", "Chairman's Message", "Message from the chairman", "I1 story.html#chairman", "G"),
    ("Our Story", "President's Message", "Message from the president", "I1 story.html#president", "G"),
    ("Our Story", "Board of Trustees", "Guardians of the Mission", "I1 story.html#leadership", "G"),
    ("Our Story", "Executive Committee", "Carrying the Work Forward", "I1 story.html#executive", "G"),
    ("Our Story", "Recognition", "Service Award recipients and Lifetime Supporters", "I1 story.html#recognition", "G"),
    ("Our Story", "Service Award — Nominate", "Nominee, relationship and reason form (v1.5)", "I2 Service Award — Nominate", "S"),
    ("Our Story", "Policies / By-Laws", "Policy cards (members' area on guest site)", "I1 story.html#governance", "G"),
    ("Our Story", "Financial Statements", "Open Books (members' area on guest site)", "I1 story.html#governance", "G"),
    ("Our Story", "Annual Meetings", "Guest: card. Signed-in: Meeting Minutes archive (Board, Executive Committee, General Body) as PDFs (v1.5)", "I1 story.html#governance · I2 Meeting Minutes", "GS"),
    ("Our Story", "Contact Us", "Address, hours, Getting here, directions", "I1 story.html#contact · I2 Help", "GS"),
    ("Our Story", "Drop Us a Line", "Contact form: name, email, message", "I1 story.html#contact", "G"),
    # ---------------------------------------------------------------- Directory & Bookings
    ("Directory & Bookings", "Jain Centers USA", "Centers (distance), pure-veg Restaurants, Business Directory with ratings and Sangha discounts (v1.5)", "I2 Jain Centers USA", "S"),
    ("Directory & Bookings", "List Your Business", "Add a business to the directory", "I2 Jain Centers USA", "S"),
    ("Directory & Bookings", "Facility Booking", "Main Hall, Upashray, Marble Lobby by date, member discount, deposit (v1.5)", "I2 Facility Booking", "S"),
    # ---------------------------------------------------------------- Account
    ("Account", "Sign in", "Member ID or email + password, Apple, Google, Forgot password", "login.html", "G"),
    ("Account", "Profile · Account", "Name, tier, donated YTD, seva hours, family count; membership tier/since/renewal and Manage", "I2 Profile", "S"),
    ("Account", "Account shortcuts", "Family Profile, Donation Receipts, Payment Methods, Recurring Subscriptions", "I2 Profile", "S"),
    ("Account", "Notification preferences", "Push/Email by category: Events, Donations, Community, Pathshala, Birthday & anniversary", "I2 Profile", "S"),
    ("Account", "Family & Dues", "Itemised dues, total, Pay All Now; family members; Add Family Member", "I2 Family & Dues", "S"),
    ("Account", "Member Card", "Public read-only member card", "I2 Member Card", "S"),
    ("Account", "Settings", "Multi-factor auth, language, text size, delete account", "I2 Settings", "S"),
    ("Account", "Explore More", "Hub for secondary features (Jinvani, Pravachan, Volunteer, Youth, Recurring Seva, Minutes, Award, About, Help)", "I2 Explore More", "S"),
    ("Account", "Log Out", "Sign out", "I2 sidebar / Profile", "S"),
    # ---------------------------------------------------------------- Site-wide
    ("Site-wide", "Header mega-menus & mobile drawer", "Seven menus: Worship, Events, Learn, Belong, Give, Gallery, Our Story; plus Sign in and Donate", "I1 header", "G"),
    ("Site-wide", "Social links", "Facebook, Twitter, Pinterest, YouTube", "I1 top bar & footer", "G"),
    ("Site-wide", "Footer", "Visit, Donate, Community and Account link columns", "I1 footer", "G"),
    ("Site-wide", "Ask JCA chat assistant", "Chat panel with suggested questions", "I1 chat-panel", "G"),
    ("Site-wide", "Member sidebar navigation", "Grouped nav: Today, Events, Givings, Community, Learning & Directory, Institution, Account", "I2 sidebar", "S"),
    ("Site-wide", "Search & command palette", "Search events/causes/members, ⌘K quick actions", "I2 topbar", "S"),
    ("Site-wide", "Notifications bell", "Dropdown of recent reminders and receipts", "I2 topbar", "S"),
]
